### ISSUE TITLE
Tracker: Missing/Wanted Commands

### ISSUE THREAD

**Issue by nakajimayoshi** [Heavy-Division/heavy-division-bot#2]
- [X] Moderation Tools 
- [x] METAR reports 
- [x] Station Info
- [x] Descent Estimator 
- [ ] Automatic thread creation for support requests. See [discord-needle](https://github.com/MarcusOtter/discord-needle) for inspiration.
- [ ] Checklist (Waiting on documentation)
- [ ] Music functionality 
- [ ] Web-hook functionality for content creators (e.g. auto-posting YT uploads in #self-promotion)
- [ ] Handling Role assignment without Zira 
- [ ] Implement a counting game (User initiates game with a command, resets if someone double counts/miscounts)
- [ ] Database commands for flight tracking (waiting on database implementation) 
- [ ] Random route generator with user constraints
- [ ] Screenshot: provide an example of how the user should take a screenshot to ask for support with the B78XH (include pfd, mfd, FMC, glareshield panel, yoke should be hidden,
